### PR TITLE
add patcher to hide backside of entities

### PR DESCRIPTION
**Pull request by asbyth**
dont merge until 1.6 is released

### CODE REVIEW

**Comment by GamingGeek** [comment]
wow patcher

**Comment by xcfrg** [comment]
pogger

**Comment by MicrocontrollersDev** [comment]
the urge to pull this and get rid of the stupid "1" gets stronger every day.
also what about when the 1.6 betas release?

**Comment by asbyth** [comment]
> also what about when the 1.6 betas release?
sure, can be done then

**Comment by 116s** [comment]
patch

**Comment by MicrocontrollersDev** [comment]
it has finally been done

**Pull request merged**
